numpy


In [ ]:
import numpy as np


dimensions

In [ ]:
a=np.array([[[]]])
a.ndim
a.shape

(1, 1, 0)

arange

In [ ]:
b=np.arange(1,10)

In [ ]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

linespace

In [ ]:
arr=np.linspace(0,2,10)
arr

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

logspace

In [ ]:
arr=np.logspace(1,6,4)
arr

array([1.00000000e+01, 4.64158883e+02, 2.15443469e+04, 1.00000000e+06])

zeros


In [ ]:
arr=np.zeros([5])
arr

array([0., 0., 0., 0., 0.])

In [ ]:
arr=np.zeros([2,3])
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

ones

In [ ]:
  arr=np.ones([2,3])
  arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr=np.ones([2,3],dtype=int)
arr

array([[1, 1, 1],
       [1, 1, 1]])

full

In [ ]:
arr=np.full([2,3],5)
arr

array([[5, 5, 5],
       [5, 5, 5]])

In [ ]:
b=np.full([2,3],5,dtype=float)
b

array([[5., 5., 5.],
       [5., 5., 5.]])

empty

In [ ]:
arr=np.empty([3,2])
arr

array([[5., 5.],
       [5., 5.],
       [5., 5.]])

random

In [ ]:
arr=np.random.rand(2,3)
arr

array([[0.06426147, 0.29636482, 0.39423021],
       [0.11708962, 0.16854142, 0.39964663]])

ramdom integers

In [ ]:
arr=np.random .randint(5,size=(2,3))
arr

array([[4, 0, 1],
       [3, 1, 2]])

numpy data type


In [ ]:
arr=np.array([1,2,3.1,4,5,])
arr

array([1. , 2. , 3.1, 4. , 5. ])

In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


list to array

In [ ]:
lst=['string',1,2,3.1,4]

In [ ]:
arr=np.array(lst)
arr

array(['string', '1', '2', '3.1', '4'], dtype='<U32')

data type
 (int32,
 int64,
 float 32,
 float 64,
 boolean(true\ false),
 complex numper,
 string)

In [ ]:
arr= np.array([1,2,3,4])
arr.dtype


dtype('int64')

In [ ]:
arr= np.array([1,2,3.1,4])
arr.dtype

dtype('float64')

In [ ]:
arr= np.array([1,2,31,4,"True"])
arr.dtype

dtype('<U21')

change data type

In [ ]:
arr= np.array([1,2,3,4] ,dtype=float)
arr.dtype

dtype('float64')

type casting

In [ ]:
arr=np.array([1,2,3,4],dtype=float)
arr.dtype

dtype('float64')

In [ ]:

arr

array([1., 2., 3., 4.])

In [ ]:
arr=np.array([1,2,3,4])
arr=arr.astype(float)
arr

array([1., 2., 3., 4.])

In [ ]:
arr=arr.astype(int)
arr

array([1, 2, 3, 4])

type casting error

In [ ]:
arr=np.array(["1","2","hello"])
arr=arr.astype(bool)# put (int) hear
arr


array([ True,  True,  True])

In [ ]:
arr=np.array([[1,2,3],
               [4,5,6]])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr.ndim

2

array reshaping

In [ ]:
arr=np.array([1,2,3,4,5,6])
reshaped=arr.reshape(3,2)
reshaped

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#ravel (back to form the reshape )
ravel = reshaped.ravel()
ravel

array([1, 2, 3, 4, 5, 6])

In [ ]:
ravel[0]=100
print(ravel)
print(reshaped)

[100   2   3   4   5   6]
[[100   2]
 [  3   4]
 [  5   6]]


flatten (copy)

In [ ]:
flat=reshaped.flatten()
flat

array([100,   2,   3,   4,   5,   6])

In [ ]:
flat[0]=1
flat

array([1, 2, 3, 4, 5, 6])

In [ ]:
reshaped

array([[100,   2],
       [  3,   4],
       [  5,   6]])

arthmetic operations

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [ ]:
#addition
print(a+b)

[5 7 9]


In [ ]:
a+b

array([5, 7, 9])

In [ ]:
#subtraction
a-b

array([-3, -3, -3])

In [ ]:
#division
a/b

array([0.25, 0.4 , 0.5 ])

In [ ]:
#integer division
b//a

array([4, 2, 2])

In [ ]:
#modulus remainder
a%b

array([1, 2, 3])

In [ ]:
#multiplication
a*b

array([ 4, 10, 18])

In [ ]:
#exponent-> power
print(a**2,b**2)

[1 4 9] [16 25 36]


universal funtion -> ufuncs  


In [ ]:
arr=np.array([1,4,9,24])

In [ ]:
print(np.sqrt(arr))

[1.         2.         3.         4.89897949]


In [ ]:
#exponentioal->np.exp -> e^x
print(np.exp([1,2]))


[2.71828183 7.3890561 ]


In [ ]:
print(np.exp(arr))

[2.71828183e+00 5.45981500e+01 8.10308393e+03 2.64891221e+10]


In [ ]:
arun=np.array([ 0,np.pi,np.pi/2])
print(np.sin(arun))

[0.0000000e+00 1.2246468e-16 1.0000000e+00]


In [ ]:
#slicing
a=[1,2,3,4,5]

In [ ]:
a[ -1:-5:-1]

[5, 4, 3, 2]

In [ ]:
a[::2]

[1, 3, 5]

In [ ]:
#negative indexing
a[-1]

5

In [ ]:
  #matrix
  matrix = np.array ([[1,2,3,],
                      [4,5,6,],
                      [7,8,9,]])

In [ ]:
print(matrix[0:2,0:])

[[1 2 3]
 [4 5 6]]


In [ ]:
print(matrix[0:2,1:3])

[[2 3]
 [5 6]]


In [ ]:
 #np.take
 arr=np.array([1,2,3,4,5,])
 ind=[1,2]
 print(np.take(arr,ind))

[2 3]


In [ ]:
#itreating with nditer()
arr=np.array([[1,2],[3,4]])
for x in np.nditer(arr):
  print( x  ,end ='  ' )

1  2  3  4  

In [ ]:
 #indenumerical
 for ind,x in np.ndenumerate(arr):
   print(ind ,arr)

(0, 0) [[1 2]
 [3 4]]
(0, 1) [[1 2]
 [3 4]]
(1, 0) [[1 2]
 [3 4]]
(1, 1) [[1 2]
 [3 4]]


In [ ]:
#view  vs copy
arr=np.array([1,2,3,4,5])
view=arr[1:3]
view

array([2, 3])

In [ ]:
view[1]=10
view

array([ 2, 10])

In [ ]:
arr

array([ 1,  2, 10,  4,  5])

In [ ]:
#copy
arr=np.array([1,2,3,4,5])
copy=arr[1:3].copy()
copy

array([2, 3])

In [ ]:
copy[1]=100
copy

array([  2, 100])

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
#transpose
arr=np.array([[1,2,3],
             [4,5,6]])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(arr.transpose())

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# swap
arr=np.array([[[1,2,3],
             [4,5,6]]])
arr.shape
swap=np.swapaxes(arr,0,2)
swap.shape

(3, 2, 1)

In [ ]:
swap=np.swapaxes(arr,0,2)
swap.shape

(3, 2, 1)

In [ ]:
arr

array([[[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
arr.shape

(1, 2, 3)

In [ ]:
swap.shape

(3, 2, 1)

In [ ]:
#concatenation
a=np.array ([[1,2,3],[4,5,6]])
b=np.array([[1,2,3,],[5,6,7]])

In [ ]:
arr=np.concatenate((a,b),axis=0)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [5, 6, 7]])

In [ ]:
a=np.array ([[1,2,3],[4,5,6]])
arr=np.vstack(a)
arr


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr=np.hstack(a)
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr=np.stack((a,b),axis=0)
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [5, 6, 7]]])

In [ ]:
arr=np.stack((a,b),axis=1)
arr

array([[[1, 2, 3],
        [1, 2, 3]],

       [[4, 5, 6],
        [5, 6, 7]]])

In [ ]:
# splitting arrays
arun= np.array ([[1,2,],[3,4],[5,6],[7,8]])
arun



array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
print(np.split(arun,2))

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [ ]:
print (np.hsplit(arun,2))

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]


In [ ]:
print(np.vsplit(arun,2))

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [ ]:
#rrepeating
print(np.repeat(arun,2))

[1 1 2 2 3 3 4 4 5 5 6 6 7 7 8 8]


In [ ]:
#tile
print(np.tile(arun,2))

[[1 2 1 2]
 [3 4 3 4]
 [5 6 5 6]
 [7 8 7 8]]


In [ ]:
#aggrigate funtion
a=np.array([1,2,3])
print(np.sum(a))

6


In [ ]:
print(np.mean(a))

2.0


In [ ]:
np.median(a)

np.float64(2.0)

In [ ]:
np.std(a)

np.float64(0.816496580927726)

In [ ]:
np.var(a)

np.float64(0.6666666666666666)

In [ ]:
np.min(a)

np.int64(1)

In [ ]:
np.max(a)

np.int64(3)

In [ ]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(np.sum(matrix,axis=0))

[12 15 18]


In [ ]:
print(np.sum(matrix,axis=1))

[ 6 15 24]


In [ ]:
#cumulative faction
a


array([1, 2, 3])

In [ ]:
print(np.cumsum(a))

[1 3 6]


In [ ]:
print(np.cumprod(a))

[1 2 6]


In [ ]:
#conditional based choice
a

array([1, 2, 3])

In [ ]:
#where
print(np.where(a>2,"yes","no"))

['no' 'no' 'yes']


In [ ]:
#argwhere
print(np.argwhere(a>2))

[[2]]


In [ ]:
#logical and
arr=np.array ([10,1,2,3,4,5,6])
a=np.logical_and(arr>3,arr<6)
print(a)

[False False False False  True  True False]


In [ ]:
arr[a]

array([4, 5])

In [ ]:
#logical or
a=np.logical_or(arr<4,arr>5)
print(a)

[ True  True  True  True False False  True]


In [ ]:
arr[a]

array([10,  1,  2,  3,  6])

In [ ]:
#nonzero
arun= np.array ([0,1,21,0,8,0,0,8,7,])
arun


array([ 0,  1, 21,  0,  8,  0,  0,  8,  7])

In [ ]:
k=np.nonzero(arun)
print(k)

(array([1, 2, 4, 7, 8]),)


In [ ]:
# broadcasting
image = np.array ([[200,150],[100,250]])
image

array([[200, 150],
       [100, 250]])

In [ ]:
brigthnees =image+50
print(brigthnees)

[[250 200]
 [150 300]]


In [ ]:
#vectorization
def squre(x):
  return x*x
vfunc=np.vectorize(squre)
print(vfunc(arun))

[  0   1 441   0  64   0   0  64  49]


In [ ]:
#dealing with missing valu
a=np.array ([1,2,np.nan,4,5])
a

array([ 1.,  2., nan,  4.,  5.])

In [ ]:
# np.inf
#np.isnan
#np.isinf
#np.isfinite#